### ISSUE TITLE
NFT Payment: CORS Policy error and failed to fetch

### ISSUE THREAD

**Issue by FedeGens** [neftyblocks/embeds#1]
environment: mainnet
domain: localhost

After the checkout page of an NFT (in the neftyblocks.me domain), while signing the transaction, two errors appear:
- CORS Policy
- Failed to fetch

**errors:**

Access to fetch at 'https://wax.neftyblocks.com/v1/chain/get_info' from origin 'https://neftyblocks.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.643ccf21.js:1

POST https://wax.neftyblocks.com/v1/chain/get_info net::ERR_FAILED 200
(anonymous) @ index.643ccf21.js:1
_ @ index.643ccf21.js:1
(anonymous) @ index.643ccf21.js:1
(anonymous) @ index.643ccf21.js:1
W @ index.643ccf21.js:1
e.fetch @ index.643ccf21.js:1
(anonymous) @ index.643ccf21.js:1
_ @ index.643ccf21.js:1
(anonymous) @ index.643ccf21.js:1
(anonymous) @ index.643ccf21.js:1
W @ index.643ccf21.js:1
e.get_info @ index.643ccf21.js:1
(anonymous) @ index.643ccf21.js:1
_ @ index.643ccf21.js:1
(anonymous) @ index.643ccf21.js:1
(anonymous) @ index.643ccf21.js:1
te @ index.643ccf21.js:1
e.transact @ index.643ccf21.js:1
(anonymous) @ index.96195812.js:1
a @ index.96195812.js:1
Promise.then (async)
u @ index.96195812.js:1
(anonymous) @ index.96195812.js:1
w @ index.96195812.js:1
api.transact @ index.96195812.js:1
signTransaction @ index.96195812.js:5
await in signTransaction (async)
dg @ index.841f0f6e.js:1
s @ index.841f0f6e.js:49
Jt @ index.841f0f6e.js:1
at @ index.841f0f6e.js:1
n @ index.841f0f6e.js:1

index.841f0f6e.js:49 Error: Failed to fetch
    at R.signTransaction (index.96195812.js:5:595)
    at async dg (index.841f0f6e.js:1:170082)
    at async s (index.841f0f6e.js:49:29759)

**Comment by mvdschee** [comment]
he @FedeGens this should be resolved now, we had not added neftyblocks.me to the CORS yet
