### ISSUE TITLE
marketplace card - stretched collection logo icon 

### ISSUE THREAD

**Issue by FedeGens** [neftyblocks/embeds#2]
The collection logo icon seems to be stretched if it hasn't a 1:1 aspect ratio. (Attached an image)

<img width="76" alt="Schermata 2022-06-30 alle 16 05 51" src="https://user-images.githubusercontent.com/22976202/176685816-d89f4101-2c12-49fa-b578-e1c1302f9f0e.png">

`object-fit: contain` may help on this.

**Comment by mvdschee** [comment]
I have implemented your styling suggestions! [version 0.4.3](https://www.npmjs.com/package/@neftyblocks/market)
