### ISSUE TITLE
Wrong card image shown

### ISSUE THREAD

**Issue by FedeGens** [neftyblocks/embeds#3]
Trying to change in a fast way the schemas (maybe while the page is still loading the previously selected schema), creates a small visual bug: the card shows the info of the correct NFTs, but the image is from the cards of the previous schema. After a while the images gets reloaded

**Comment by mvdschee** [comment]
I have published a new [version 0.4.3](https://www.npmjs.com/package/@neftyblocks/market) the ghosting should not happen anymore, we only let the last changes reload any information on the market
