### ISSUE TITLE
I cannot buy with the cloud wallet

### ISSUE THREAD

**Issue by jandrad** [neftyblocks/embeds#4]
When purchasing an NFT using the cloud wallet it stays in a loading state.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/227524/177578451-73f69066-61fa-4420-84e2-a4c5302f3368.png">

![image](https://user-images.githubusercontent.com/227524/177578718-fa748e90-b22c-4b87-8d94-428776ed90ff.png)

**Comment by mvdschee** [comment]
Okay let me check that one

**Comment by mvdschee** [comment]
I checked and the code works if I run it on a localhost, so I started to check the logs and it looks like WCW blocking neftyblocks.me because it looks like neftyblocks.com.

this is the response from their api
```
error: "ForbiddenTransactionException"
message: "Malicious website blocked"
```

**Comment by mvdschee** [comment]
A ticket has been submitted to the Wax team, waiting for a response

**Comment by jandrad** [comment]
> A ticket has been submitted to the Wax team, waiting for a response

Thanks Max!

**Comment by mvdschee** [comment]
Wax has whitelisted the domain and this issue has been resolved
