### ISSUE TITLE
Show WAX balance within marketplace

### ISSUE THREAD

**Issue by Diegenft** [neftyblocks/embeds#6]
Show wax balance of user within marketplace and handle update of wax balance instantly after marketplace actions (purchases)

Noticed lack of wax balance when accessing taco embedded marketplace using mobile phone device.

**Comment by mvdschee** [comment]
**edit**

He @Diegenft for the payment flow you are going to another website where we keep track of the wax balance, we run this on our own domain to provide a secure environment for the user to do transactions and login, showing user information would be outside the scope of the marketplace
